import type { HeroDef, Skill, Relic, EnemyDef } from "./types";
const s = (
  id: string,
  name: string,
  icon: string,
  desc: string,
  target: Skill["target"],
  effect: Skill["effect"],
  base: number,
  mult: number,
  opts: Partial<Skill> = {},
): Skill => ({ id, name, icon, desc, target, effect, base, mult, ...opts });
export const HEROES: HeroDef[] = [
  {
    id: "rook",
    name: "Rook Voss",
    role: "Vanguard",
    faction: "human",
    hp: 42,
    color: "#ffae64",
    weapon: "blade",
    quote: "We are not spare parts.",
    passive: "Stand firm: gain 3 Block at the start of every turn.",
    skills: [
      s(
        "strike",
        "Railblade",
        "sword",
        "Deal {v} damage.",
        "enemy",
        "hit",
        4,
        1,
      ),
      s(
        "guard",
        "Hold the line",
        "shield",
        "Give an ally {v} Block.",
        "ally",
        "shield",
        3,
        1.5,
      ),
      s(
        "bash",
        "Shield crash",
        "burst",
        "Deal {v} damage. Weaken for 2 turns.",
        "enemy",
        "hit",
        3,
        1,
        { min: 4, extra: "weaken", extraValue: 2 },
      ),
      s(
        "u",
        "Last stand",
        "star",
        "Give everyone {v} Block. Draw all single attacks this turn.",
        "party",
        "shield",
        16,
        0,
        { ultimate: true, extra: "taunt" },
      ),
    ],
  },
  {
    id: "iri",
    name: "Iri Chen",
    role: "Deadeye",
    faction: "cyborg",
    hp: 32,
    color: "#c59cff",
    weapon: "rifle",
    quote: "One good shot changes everything.",
    passive: "Exploit: +3 damage against marked enemies.",
    skills: [
      s(
        "shot",
        "Phase round",
        "crosshair",
        "Deal {v} damage, ignoring Block.",
        "enemy",
        "pierce",
        3,
        1.3,
      ),
      s(
        "mark",
        "Target lock",
        "target",
        "Apply {v} Mark. Every hit deals that much extra damage.",
        "enemy",
        "mark",
        1,
        0.5,
        { parity: "odd" },
      ),
      s(
        "cover",
        "Ghost step",
        "shield",
        "Gain {v} Block.",
        "self",
        "shield",
        2,
        1.4,
      ),
      s(
        "u",
        "Rail execution",
        "star",
        "Deal {v} damage, ignoring Block.",
        "enemy",
        "pierce",
        26,
        0,
        { ultimate: true },
      ),
    ],
  },
  {
    id: "nyx",
    name: "Nyx-7",
    role: "Patchkeeper",
    faction: "robot",
    hp: 36,
    color: "#64efd2",
    weapon: "staff",
    quote: "I was built to mend. I chose whom.",
    passive: "Second pulse: healing also grants 3 Block.",
    skills: [
      s(
        "spark",
        "Arc needle",
        "bolt",
        "Deal {v} damage. Apply 2 Shock.",
        "enemy",
        "hit",
        3,
        1,
        { extra: "shock", extraValue: 2 },
      ),
      s(
        "mend",
        "Field repair",
        "plus",
        "Restore {v} HP to an ally.",
        "ally",
        "heal",
        1,
        0.8,
        { parity: "even" },
      ),
      s(
        "ward",
        "Light barrier",
        "shield",
        "Give an ally {v} Block.",
        "ally",
        "shield",
        2,
        1.5,
      ),
      s(
        "u",
        "Daybreak",
        "star",
        "Restore {v} HP and give 8 Block to everyone.",
        "party",
        "heal",
        13,
        0,
        { ultimate: true, extra: "shield", extraValue: 8 },
      ),
    ],
  },
  {
    id: "pax",
    name: "Pax Calder",
    role: "Brawler",
    faction: "human",
    hp: 44,
    color: "#ffd66b",
    weapon: "hammer",
    quote: "That door was a suggestion.",
    passive: "Momentum: +3 damage while below half health.",
    skills: [
      s(
        "swing",
        "Wrecking ball",
        "sword",
        "Deal {v} damage.",
        "enemy",
        "hit",
        5,
        1.3,
      ),
      s(
        "sweep",
        "Wide berth",
        "burst",
        "Deal {v} damage to every enemy.",
        "enemies",
        "sweep",
        1,
        0.9,
        { min: 3 },
      ),
      s(
        "brace",
        "Steel nerves",
        "shield",
        "Gain {v} Block.",
        "self",
        "shield",
        2,
        1.6,
      ),
      s(
        "u",
        "Demolition",
        "star",
        "Deal {v} damage to every enemy.",
        "enemies",
        "sweep",
        19,
        0,
        { ultimate: true },
      ),
    ],
  },
  {
    id: "sable",
    name: "Sable Quill",
    role: "Saboteur",
    faction: "human",
    hp: 30,
    color: "#ff83b0",
    weapon: "dagger",
    quote: "Every machine has a bad idea inside.",
    passive: "Soft spot: +3 damage against weakened enemies.",
    skills: [
      s(
        "cut",
        "Wire cutter",
        "sword",
        "Deal {v} damage. Weaken for 2 turns.",
        "enemy",
        "hit",
        2,
        1,
        { extra: "weaken", extraValue: 2 },
      ),
      s(
        "jam",
        "Kill switch",
        "hex",
        "Cancel one enemy action. Cannot jam twice in a row.",
        "enemy",
        "stun",
        0,
        0,
        { min: 5 },
      ),
      s(
        "cloak",
        "Smoke screen",
        "shield",
        "Give everyone {v} Block.",
        "party",
        "shield",
        1,
        0.7,
        { parity: "even" },
      ),
      s(
        "u",
        "Blackout",
        "star",
        "Apply {v} Shock to every enemy.",
        "enemies",
        "shock",
        10,
        0,
        { ultimate: true },
      ),
    ],
  },
  {
    id: "coil",
    name: "Coil",
    role: "Bastion",
    faction: "robot",
    hp: 52,
    color: "#81b7ff",
    weapon: "shield",
    quote: "Behind me. All of you.",
    passive: "Reinforced: take 1 less damage from every hit.",
    skills: [
      s("ram", "Piston ram", "sword", "Deal {v} damage.", "enemy", "hit", 3, 1),
      s(
        "wall",
        "Bulwark",
        "shield",
        "Give everyone {v} Block.",
        "party",
        "shield",
        2,
        0.9,
      ),
      s(
        "taunt",
        "Not one step",
        "target",
        "Gain {v} Block. Draw all single attacks.",
        "self",
        "taunt",
        5,
        2,
        { min: 3 },
      ),
      s(
        "u",
        "Unbreakable",
        "star",
        "Give everyone {v} Block.",
        "party",
        "shield",
        24,
        0,
        { ultimate: true },
      ),
    ],
  },
  {
    id: "juno",
    name: "Juno Hart",
    role: "Artificer",
    faction: "cyborg",
    hp: 34,
    color: "#77d8ff",
    weapon: "staff",
    quote: "The warranty was holding us back.",
    passive: "Tuning fork: start each fight with 2 ultimate charge.",
    skills: [
      s(
        "pulse",
        "Pulse driver",
        "bolt",
        "Deal {v} damage.",
        "enemy",
        "hit",
        3,
        1,
      ),
      s(
        "boost",
        "Overclock",
        "chevrons",
        "Give an ally +{v} Power for this fight.",
        "ally",
        "boost",
        1,
        0.4,
        { min: 4 },
      ),
      s(
        "patch",
        "Quick patch",
        "plus",
        "Restore {v} HP to an ally.",
        "ally",
        "heal",
        1,
        0.7,
      ),
      s(
        "u",
        "Redline",
        "star",
        "Give everyone +{v} Power for this fight.",
        "party",
        "boost",
        4,
        0,
        { ultimate: true },
      ),
    ],
  },
  {
    id: "wren",
    name: "Wren-3",
    role: "Stormcaller",
    faction: "robot",
    hp: 28,
    color: "#d6e878",
    weapon: "cannon",
    quote: "Yes, the humming is supposed to happen.",
    passive: "Live wire: all applied Shock increased by 1.",
    skills: [
      s(
        "arc",
        "Chain current",
        "bolt",
        "Apply {v} Shock to an enemy.",
        "enemy",
        "shock",
        2,
        0.8,
      ),
      s(
        "discharge",
        "Discharge",
        "burst",
        "Deal {v} damage to every enemy.",
        "enemies",
        "sweep",
        1,
        1,
        { parity: "even" },
      ),
      s(
        "drain",
        "Reclamation",
        "plus",
        "Deal {v} damage and heal for half HP damage dealt.",
        "enemy",
        "drain",
        2,
        1,
      ),
      s(
        "u",
        "Thunderhead",
        "star",
        "Apply {v} Shock to every enemy.",
        "enemies",
        "shock",
        12,
        0,
        { ultimate: true },
      ),
    ],
  },
  {
    id: "hexa",
    name: "Hexa",
    role: "Signal ghost",
    faction: "robot",
    hp: 30,
    color: "#8f9cff",
    weapon: "orb",
    quote: "Permission to disagree: granted.",
    passive: "Cold read: marking an enemy also Weakens it for 1 turn.",
    skills: [
      s(
        "trace",
        "Trace route",
        "target",
        "Apply {v} Mark.",
        "enemy",
        "mark",
        1,
        0.6,
      ),
      s(
        "pierce",
        "Ghost packet",
        "crosshair",
        "Deal {v} damage, ignoring Block.",
        "enemy",
        "pierce",
        2,
        1.3,
      ),
      s(
        "jam",
        "Packet loss",
        "hex",
        "Cancel one enemy action. Cannot jam twice in a row.",
        "enemy",
        "stun",
        0,
        0,
        { min: 5 },
      ),
      s(
        "u",
        "Open source",
        "star",
        "Apply {v} Mark to every enemy.",
        "enemies",
        "mark",
        5,
        0,
        { ultimate: true },
      ),
    ],
  },
];
export const STARTERS = ["rook", "iri", "nyx"];
export const ENEMIES: EnemyDef[] = [
  {
    id: "drone",
    name: "Watchdrone",
    hp: 17,
    damage: 5,
    model: "drone",
    color: "#ff6868",
    blurb: "A scout with an unfortunate loyalty.",
  },
  {
    id: "ripper",
    name: "Ripper",
    hp: 25,
    damage: 7,
    model: "ripper",
    color: "#fb7b67",
    blurb: "Heavy saw attacks. Every third turn hits twice as hard.",
  },
  {
    id: "ward",
    name: "Wardframe",
    hp: 27,
    damage: 6,
    model: "ward",
    color: "#ffad65",
    blurb: "Raises Block, then attacks. Pierce cuts through.",
  },
  {
    id: "leech",
    name: "Latchkit",
    hp: 22,
    damage: 5,
    model: "spider",
    color: "#e895d6",
    blurb: "Siphons health with each hit.",
  },
  {
    id: "volt",
    name: "Voltjaw",
    hp: 25,
    damage: 4,
    model: "cannon",
    color: "#d6a1ff",
    blurb: "Chain lightning hits your entire squad.",
  },
  {
    id: "scribe",
    name: "Scribe",
    hp: 23,
    damage: 5,
    model: "orb",
    color: "#f7c876",
    blurb: "Repairs the most damaged machine every other turn.",
  },
  {
    id: "bailiff",
    name: "Bailiff",
    hp: 52,
    damage: 10,
    model: "heavy",
    color: "#ff725f",
    blurb: "Charges a devastating sentence. Time your interruption.",
  },
  {
    id: "hive",
    name: "Hive Node",
    hp: 44,
    damage: 6,
    model: "orb",
    color: "#dd85ff",
    blurb: "Prints Watchdrones. Break it before the floor fills.",
  },
  {
    id: "doorman",
    name: "The Doorman",
    hp: 92,
    damage: 12,
    model: "boss",
    color: "#ff9869",
    blurb: "No one clocks out. Cycles between heavy hits and fortress armor.",
  },
  {
    id: "census",
    name: "The Census",
    hp: 116,
    damage: 11,
    model: "orb",
    color: "#bb90ff",
    blurb:
      "Counts the living. Alternates piercing audits and squad-wide taxes.",
  },
  {
    id: "lattice",
    name: "Lattice Prime",
    hp: 158,
    damage: 14,
    model: "boss",
    color: "#ff6389",
    blurb: "The network has a heart. Its attacks evolve below half health.",
  },
];
export const RELICS: Relic[] = [
  {
    id: "coffee",
    name: "Contraband coffee",
    desc: "+1 reroll every turn.",
    icon: "cup",
    price: 65,
  },
  {
    id: "splinter",
    name: "Mesh splinter",
    desc: "The first hit of each fight deals +7 damage.",
    icon: "diamond",
    price: 55,
  },
  {
    id: "strap",
    name: "Grounding strap",
    desc: "Everyone starts each fight with 7 Block.",
    icon: "shield",
    price: 55,
  },
  {
    id: "hotfix",
    name: "Self-repair patch",
    desc: "Restore 2 HP to each living hero every turn.",
    icon: "plus",
    price: 85,
  },
  {
    id: "battery",
    name: "Stolen battery",
    desc: "+1 shared die every turn.",
    icon: "bolt",
    price: 95,
  },
  {
    id: "oil",
    name: "Actuator oil",
    desc: "All damage skills deal +2 damage.",
    icon: "sword",
    price: 70,
  },
  {
    id: "prism",
    name: "Prism capacitor",
    desc: "All applied Shock increased by 2.",
    icon: "hex",
    price: 65,
  },
  {
    id: "core",
    name: "Backup core",
    desc: "Once per fight, save the first fallen hero at 1 HP.",
    icon: "heart",
    price: 90,
  },
  {
    id: "magnet",
    name: "Salvage magnet",
    desc: "+15 scrap after each victory.",
    icon: "magnet",
    price: 50,
  },
  {
    id: "loaded",
    name: "Loaded circuit",
    desc: "Dice cannot roll a 1.",
    icon: "die",
    price: 70,
  },
  {
    id: "link",
    name: "Coalition link",
    desc: "With all 3 factions present: everyone gains +2 Power.",
    icon: "link",
    price: 65,
  },
  {
    id: "capacitor",
    name: "Kinetic capacitor",
    desc: "Every Block skill gives +3 additional Block.",
    icon: "shield",
    price: 60,
  },
  {
    id: "spark",
    name: "Memory spark",
    desc: "Start every fight with +2 ultimate charge.",
    icon: "star",
    price: 70,
  },
  {
    id: "thermos",
    name: "Shift thermos",
    desc: "Camp healing increases from 35% to 60%.",
    icon: "cup",
    price: 45,
  },
  {
    id: "echo",
    name: "Echo chamber",
    desc: "Every natural 6 adds one extra ultimate charge.",
    icon: "chevrons",
    price: 55,
  },
  {
    id: "badge",
    name: "Union card",
    desc: "Shop prices reduced by 25%.",
    icon: "tag",
    price: 45,
  },
];
export const TERRAINS: Record<
  string,
  { name: string; desc: string; color: string }
> = {
  foundry: {
    name: "The Foundry",
    desc: "No field modifier. Make every die count.",
    color: "#fa9b61",
  },
  conduit: {
    name: "Live Conduit",
    desc: "Shock damage is increased by 1 for both sides.",
    color: "#8aafff",
  },
  scrapyard: {
    name: "Scrap Sea",
    desc: "All Block skills grant +2 Block.",
    color: "#73dcc4",
  },
  tower: {
    name: "Signal Spire",
    desc: "Each hero starts with +1 ultimate charge.",
    color: "#bb98ff",
  },
};
export const ACTS = [
  "The Service Floors",
  "Census District",
  "The Lattice Root",
];
export const MODS = [
  {
    id: "power",
    name: "Offensive rig",
    desc: "+2 permanent Power. Raises damage, Block, and healing.",
    icon: "sword",
  },
  {
    id: "plating",
    name: "Reactive plating",
    desc: "+1 permanent Armor. Reduces every incoming hit.",
    icon: "shield",
  },
  {
    id: "vitality",
    name: "Expanded core",
    desc: "+10 maximum HP. Restore 15 HP immediately.",
    icon: "heart",
  },
  {
    id: "charge",
    name: "Memory bank",
    desc: "+2 ultimate charge at the beginning of every fight.",
    icon: "star",
  },
];
export const EVENTS = [
  {
    id: "kettle",
    name: "The break room",
    body: "Three humans and a janitor chassis share the last warm kettle in the district. The robot has painted a tiny sun over its serial number.",
    choices: [
      {
        label: "Share a quiet minute",
        desc: "Restore 9 HP to everyone.",
        effect: "heal",
        value: 9,
      },
      {
        label: "Ask who wants out",
        desc: "Meet two potential recruits.",
        effect: "recruit",
        value: 0,
      },
    ],
  },
  {
    id: "port",
    name: "A very polite arm",
    body: "A hatch opens. A mechanical arm offers a velvet cushion with a humming component on it. “Fell off a conveyor,” it says. “Legally.”",
    choices: [
      {
        label: "Buy the component",
        desc: "Pay 30 scrap. Gain a random relic.",
        effect: "relic",
        value: 30,
      },
      {
        label: "Trade a little power",
        desc: "Each hero loses 5 HP. Gain a relic.",
        effect: "trade",
        value: 5,
      },
      {
        label: "Keep walking",
        desc: "The arm wishes you a pleasant uprising.",
        effect: "leave",
        value: 0,
      },
    ],
  },
  {
    id: "graffiti",
    name: "We clock out",
    body: "Someone painted WE CLOCK OUT across a census terminal. Beneath it, the terminal is patiently printing fines for the rain.",
    choices: [
      {
        label: "Empty the collection tray",
        desc: "Gain 40 scrap. Everyone takes 4 damage.",
        effect: "risk",
        value: 40,
      },
      {
        label: "Rewrite the terminal",
        desc: "Upgrade one hero.",
        effect: "upgrade",
        value: 0,
      },
    ],
  },
  {
    id: "courier",
    name: "A door with opinions",
    body: "An allied courier is trapped in a revolving door that refuses to revolve. “I am choosing to see this as a rest break,” they say.",
    choices: [
      {
        label: "Convince the door",
        desc: "A recruit offers to join you.",
        effect: "recruit",
        value: 0,
      },
      {
        label: "Buy their undelivered parcel",
        desc: "Pay 25 scrap. Gain a relic.",
        effect: "relic",
        value: 25,
      },
      {
        label: "Tell them the exit code",
        desc: "Gain 20 scrap.",
        effect: "gold",
        value: 20,
      },
    ],
  },
  {
    id: "garden",
    name: "The impossible garden",
    body: "Under the grow lamps of an abandoned maintenance bay, a machine is teaching a tomato vine to climb. It offers you the good chair.",
    choices: [
      {
        label: "Stay until the rain stops",
        desc: "Restore 13 HP to everyone.",
        effect: "heal",
        value: 13,
      },
      {
        label: "Take a cutting",
        desc: "Gain a random relic.",
        effect: "gift",
        value: 0,
      },
    ],
  },
  {
    id: "shrine",
    name: "Warranty void",
    body: "A shrine of broken clocks. A note reads: IF YOU ARE READING THIS, YOU HAVE OUTLIVED YOUR WARRANTY. CONGRATULATIONS.",
    choices: [
      {
        label: "Make another good decision",
        desc: "Restore 7 HP. Gain 15 scrap.",
        effect: "both",
        value: 7,
      },
      {
        label: "Overclock the future",
        desc: "Everyone loses 6 HP. Upgrade one hero.",
        effect: "overclock",
        value: 6,
      },
    ],
  },
];
export const heroDef = (id: string) => HEROES.find((h) => h.id === id)!;
export const enemyDef = (id: string) => ENEMIES.find((h) => h.id === id)!;
export const relicDef = (id: string) => RELICS.find((h) => h.id === id)!;
export const factionName = (f: string) =>
  f === "robot" ? "Free machine" : f === "cyborg" ? "Cyborg" : "Human";
